require(plyr)
#train <- read.csv('testingSetStem.csv', stringsAsFactors = F)
df <- read.csv('trainingSetNormalStem.csv', stringsAsFactors = F)
getSub1 <- subset(df, is_kelas==1)
getCount1 <- sum(getSub1$tapi)
print(getCount1)
getSub_1 <- subset(df, is_kelas==-1)
getCount_1 <- sum(getSub_1$tapi)
print(getCount_1)
getSub0 <- subset(df, is_kelas==0)
getCount0 <- sum(getSub0$tapi)
print(getCount0)

train$is_kelas <- factor(train$is_kelas)
res <- count(train$is_kelas)
print(res)
