require(dplyr)
require(stringr)
require(data.table)
require(tm)
require(Matrix)
require(e1071)
require(katadasaR)
require(devtools)
require(qdapRegex)

traine <- read.csv('cobacektrain.csv', stringsAsFactors = F)
new_train <- read.csv('cobatest.csv', stringsAsFactors = F)
train <- rbind(traine, new_train)

train$text <- gsub( "\\b(aaamin|aamiin|amien|amiiiiin|amiiiinnnnn|amiin|aminn|aminnnnnnn)\\b" , "amin", train$text)
train$text <- gsub( "\\b(agy|ahy|agus|gus|sylvi)\\b" , "agussylvi", train$text)
train$text <- gsub( "\\b(aaah|ahh|akh)\\b" , "ah", train$text)
train$text <- gsub( "\\b(ahahaha|wakakaka|hahaa|hahaaaa|hahaahah|hahah|hahaha|hahahaa|hahahah|hahahaha|hahahahaasem|hahahahhahahahahhahahahahhaahahahahahha|hahahha|hahahhaha|hahhaa|hakhakhak|hakhakhakhak|wkwk|wkwkk|wkwkkw|wkwkwk|wkwkwkw|wkwkwkwkw|wkwkwkwkwk|wwwkkkkkkkkk)\\b" , "haha", train$text)
train$text <- gsub( "\\b(ahamdulillah|alhamdulilah|alhamdullilah|alhmdlh)\\b" , "alhamdulillah", train$text)
train$text <- gsub( "\\b(ahoax|ahok|ahoklah|ahooook|ahox|djarot)\\b" , "ahokdjarot", train$text)
train$text <- gsub( "\\b(ahokers)\\b" , "ahoker", train$text)
train$text <- gsub( "\\b(aja|ajaa|ajah|aje|ajee)\\b" , "saja", train$text)
train$text <- gsub( "\\b(alesan|alasn|alesannye)\\b" , "alasan", train$text)
train$text <- gsub( "\\b(alloh|allooh)\\b" , "allah", train$text)
train$text <- gsub( "\\b(ampe|smp|smpe|sampe)\\b" , "sampai", train$text)
train$text <- gsub( "\\b(analisis)\\b" , "analisa", train$text)
train$text <- gsub( "\\b(bktikan)\\b" , "bukti", train$text)
train$text <- gsub( "\\b(akhlaq)\\b" , "akhlak", train$text)
train$text <- gsub( "\\b(ayoo|ayoooo|ayuk|yuk|yuuuk)\\b" , "ayo", train$text)
train$text <- gsub( "\\b(kritisi)\\b" , "kritis", train$text)
train$text <- gsub( "\\b(asik)\\b" , "asyik", train$text)
train$text <- gsub( "\\b(mentri|mendikbud|mentrinya|mendiknas|menkeu)\\b" , "menteri", train$text)
train$text <- gsub( "\\b(gak|enggak|tdk|ngga|tak)\\b" , "tidak", train$text)
train$text <- gsub( "\\b(bang|mas)\\b" , "abang", train$text)
train$text <- gsub( "\\b(malem|mlm)\\b" , "malam", train$text)
train$text <- gsub( "\\b(thd)\\b" , "terhadap", train$text)
train$text <- gsub( "\\b(yak|yah|yach|yaa|yaaa|yaaaaahhh|yaaak|yaahhh|yahh|yahhh|yak|yakk)\\b" , "ya", train$text)
train$text <- gsub( "\\b(team)\\b" , "tim", train$text)
train$text <- gsub( "\\b(tmn|temanteman)\\b" , "teman", train$text)
train$text <- gsub( "\\b(tangkep)\\b" , "tangkap", train$text)
train$text <- gsub( "\\b(sgera)\\b" , "segera", train$text)
train$text <- gsub( "\\b(opo)\\b" , "apa", train$text)
train$text <- gsub( "\\b(sodara|sdr)\\b" , "saudara", train$text)
train$text <- gsub( "\\b(rb)\\b" , "ribu", train$text)
train$text <- gsub( "\\b(cma|cm)\\b" , "cuma", train$text)
train$text <- gsub( "\\b(moga|smoga)\\b" , "semoga", train$text)
train$text <- gsub( "\\b(masal)\\b" , "massal", train$text)
train$text <- gsub( "\\b(dkung)\\b" , "dukung", train$text)
train$text <- gsub( "\\b(pepo|sebeye|peppo|peponya)\\b" , "sby", train$text)
train$text <- gsub( "\\b(ngomong|ngomongin)\\b" , "omong", train$text)
train$text <- gsub( "\\b(slm)\\b" , "salam", train$text)
train$text <- gsub( "\\b(smangat)\\b" , "semangat", train$text)
train$text <- gsub( "\\b(pak|bpk)\\b" , "bapak", train$text)
train$text <- gsub( "\\b(tny|ditanya)\\b" , "tanya", train$text)
train$text <- gsub( "\\b(piye|gimana|gmn)\\b" , "bagaimana", train$text)
train$text <- gsub( "\\b(blm)\\b" , "belum", train$text)
train$text <- gsub( "\\b(klo|kalo)\\b" , "kalau", train$text)
train$text <- gsub( "\\b(skrg)\\b" , "sekarang", train$text)
train$text <- gsub( "\\b(nis|nies|anies|anis|anisbaswedan|anissandi|baswedan|sandi|sandiaga|sandiagoo|sandie|sandinuno|sandy)\\b" , "aniessandi", train$text)
train$text <- gsub( "\\b(doank)\\b" , "doang", train$text)
train$text <- gsub( "\\b(ehh)\\b" , "eh", train$text)
train$text <- gsub( "\\b(ente|lu|loe|sampeyan|sampean)\\b" , "kamu", train$text)
train$text <- gsub( "\\b(gub|gubenur|gubnernur|gubnr)\\b" , "gubernur", train$text)
train$text <- gsub( "\\b(trus|trs)\\b" , "terus", train$text)
train$text <- gsub( "\\b(kasi)\\b" , "kasih", train$text)
train$text <- gsub( "\\b(loh|lohhhh)\\b" , "lho", train$text)
train$text <- gsub( "\\b(liat)\\b" , "lihat", train$text)
train$text <- gsub( "\\b(udah|udh)\\b" , "sudah", train$text)
train$text <- gsub( "\\b(wkt)\\b" , "waktu", train$text)
train$text <- gsub( "\\b(napa|knapa|knp)\\b" , "kenapa", train$text)
train$text <- gsub( "\\b(jgn|jng)\\b" , "jangan", train$text)
train$text <- gsub( "\\b(tuhh)\\b" , "tuh", train$text)
train$text <- gsub( "\\b(puun)\\b" , "pun", train$text)
train$text <- gsub( "\\b(pny|pnya|puny)\\b" , "punya", train$text)
train$text <- gsub( "\\b(pdhl|pdahal)\\b" , "padahal", train$text)
train$text <- gsub( "\\b(nnti|nti)\\b" , "nanti", train$text)
train$text <- gsub( "\\b(duh|haduh|haduhh|haddeuh|hadeew|hadehh|hadeuhh)\\b" , "aduh", train$text)
train$text <- gsub( "\\b(bohongin|bohoooong|bohoooong)\\b" , "bohong", train$text)
train$text <- gsub( "\\b(wowo)\\b" , "prabowo", train$text)
train$text <- gsub( "\\b(aku|gue|gw|sy)\\b" , "saya", train$text)
train$text = gsub("\\s+"," ",train$text)
train$text <- trimws(train$text)
write.csv(train[1:2353,1:2],"trainNormalSVM.csv")
write.csv(train[2354:3153,1:2],"testNormalSVM.csv")